services:
  issuer:
    image: waltid/issuer-api:1.0.2402150920-SNAPSHOT
    restart: on-failure
    ports:
      - "${WALTID_ISSUER_PUBLIC_PORT:-7002}:7002"
    volumes:
      - ./config-issuer:/waltid-issuer-api/config
  verifier:
    image: waltid/verifier-api:1.0.2402150920-SNAPSHOT
    restart: on-failure
    ports:
      - "${WALTID_VERIFIER_PUBLIC_PORT:-7003}:7003"
    volumes:
      - ./config-verifier:/waltid-verifier-api/config
  wallet-anchor:
    image: waltid/wallet-api:1.0.2402150920-SNAPSHOT
    restart: on-failure
    ports:
      - "${WALTID_WALLET_ANCHOR_PUBLIC_PORT:-7001}:7001"
    volumes:
      - wallet-anchor-data:/waltid-wallet-api/data
      - ./config-wallet-anchor:/waltid-wallet-api/config
  wallet-provider:
    image: waltid/wallet-api:1.0.2402150920-SNAPSHOT
    restart: on-failure
    ports:
      - "${WALTID_WALLET_PROVIDER_PUBLIC_PORT:-7051}:7001"
    volumes:
      - wallet-provider-data:/waltid-wallet-api/data
      - ./config-wallet-provider:/waltid-wallet-api/config
  wallet-consumer:
    image: waltid/wallet-api:1.0.2402150920-SNAPSHOT
    restart: on-failure
    ports:
      - "${WALTID_WALLET_CONSUMER_PUBLIC_PORT:-7051}:7001"
    volumes:
      - wallet-consumer-data:/waltid-wallet-api/data
      - ./config-wallet-consumer:/waltid-wallet-api/config
volumes:
  wallet-anchor-data: {}
  wallet-provider-data: {}
  wallet-consumer-data: {}
